<a href="https://colab.research.google.com/github/miller00315/ia_studies/blob/main/knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from sklearn.neighbors import KNeighborsClassifier
from  sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import numpy as np

In [6]:
base = pd.read_csv('mt_cars.csv')

base.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [9]:
X = base[['mpg', 'hp']].values

y = base['cyl'].values

In [38]:
knn = KNeighborsClassifier(n_neighbors=3)

model = knn.fit(X, y)

In [39]:
predictions = model.predict(X)

print(predictions)

[6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 8 8 6]


In [40]:
accuracy = accuracy_score(y, predictions)

precision = precision_score(y, predictions, average='weighted') # Com peso

recall = recall_score(y, predictions, average='weighted')

f1 = f1_score(y, predictions, average='weighted')

print(f'Acurácia: {accuracy}, precisão: {precision}, recall: {recall}, F1: {f1}')

Acurácia: 0.9375, precisão: 0.9395833333333333, recall: 0.9375, F1: 0.9372947454844006


In [41]:
cm = confusion_matrix(y, predictions)

print(cm)

[[10  1  0]
 [ 0  6  1]
 [ 0  0 14]]


In [42]:
new_data = np.array([[19.3, 105]])

prediction_it = model.predict(new_data)

print(prediction_it)

[6]


In [43]:
distancies, indexes = model.kneighbors(new_data)

print(distancies)

print(indexes)

[[1.2        4.5177428  5.28109837]]
[[ 5 31  1]]


In [45]:
base.loc[[5, 31, 1], ["cyl", "mpg", "hp"]]

cyl   mpg   hp
5     6  18.1  105
31    4  21.4  109
1     6  21.0  110

In [18]:
import pickle

import random
num = random.random()
# save the model to disk
filename = f'finalized_{num}_{accuracy}_model.sav'

pickle.dump(model, open(filename, 'wb'))