<a href="https://colab.research.google.com/github/miller00315/ia_studies/blob/main/python_tips.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Definir a versão da biblioteca**

In [1]:
%tensorflow_version 2.x

In [7]:
import tensorflow as tf
import seaborn as sns
import numpy as np

In [5]:
tf.__version__

'2.15.0'

In [8]:
mylist = [1,2,3,4,5]

In [9]:
np.array(mylist)

array([1, 2, 3, 4, 5])

In [10]:
nested_list = [[1,2], [3,4], [5,6]]

In [11]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [12]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [25]:
np.random.rand(2)

array([0.53598146, 0.08014197])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.random.rand(2,2)

array([[0.29426997, 0.78427781],
       [0.77348553, 0.68804407]])

In [28]:
np.random.randn(5,5)

array([[-0.07480963,  0.10626242,  0.29077401, -1.66550874,  0.07319083],
       [ 2.47489536,  0.77559385,  1.27777448,  0.06671473, -0.95110284],
       [-1.00974459,  0.64873494, -0.58435478, -0.73883029, -0.99723725],
       [-0.21937906,  0.09104387, -0.32797212,  0.75579004, -0.82773938],
       [-0.83338405,  0.39938559, -0.97145074,  0.14131276, -0.23625495]])

In [32]:
np.random.randint(0, 45, 10)

array([ 2, 31,  7, 10, 27, 39, 29, 40, 24, 34])

In [31]:
np.random.randint(0, 45)

44

In [33]:
np.random.randint(0, 45, (10, 5))

array([[17, 31, 35,  2,  4],
       [12,  0, 42, 24, 19],
       [33, 38, 41,  5, 39],
       [19, 37,  8, 28, 20],
       [29, 24, 29,  9, 31],
       [42, 32, 24, 19, 13],
       [ 1, 26, 10, 21, 12],
       [11, 24,  0, 24,  1],
       [10, 35, 12, 26, 24],
       [11, 11, 16, 33, 19]])

In [34]:
np.random.seed(42)

np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [39]:
np.random.rand(4)

array([0.61185289, 0.13949386, 0.29214465, 0.36636184])

In [40]:
arr = np.arange(25)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr = np.random.randint(0, 50, 10)

In [43]:
ranarr

array([46, 43,  2, 36,  6, 20,  8, 38, 17,  3])

In [44]:
arr.shape

(25,)

In [47]:
arr = arr.reshape(5,5)

In [48]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
ranarr.max()

46

In [50]:
ranarr.argmax()

0

In [51]:
ranarr.argmin()

2

In [52]:
ranarr.dtype

dtype('int64')

In [53]:
myarr = np.random.rand(4)

In [54]:
myarr

array([0.94220176, 0.56328822, 0.3854165 , 0.01596625])

In [55]:
myarr.dtype

dtype('float64')

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0, 11)

In [12]:
slice_of_arr = arr[0:5]

In [14]:
slice_of_arr[:] = 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [18]:
arr_copy = arr.copy()

In [20]:
arr_copy[:] = 100

In [21]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [22]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [23]:
arr_2d = np.array([[5, 10, 15],[20, 25, 30], [35, 40, 45]])

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d.shape

(3, 3)

In [26]:
arr_2d[0]

array([ 5, 10, 15])

In [27]:
arr_2d[2]

array([35, 40, 45])

In [30]:
arr_2d[1,1]

25

In [34]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [35]:
arr = np.arange(1, 11)

In [36]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [38]:
bool_array = arr > 4

In [39]:
arr[bool_array]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [28]:
arr_2d[-1]

array([35, 40, 45])

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
arr / arr

<ipython-input-16-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [17]:
1 / arr

<ipython-input-17-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [18]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [19]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [20]:
np.log(arr)

<ipython-input-20-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [21]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr.sum()

45

In [23]:
arr.mean()

4.5

In [24]:
arr.var()

8.25

In [26]:
arr.std()

2.8722813232690143

In [29]:
arr2d = np.arange(0, 25).reshape(5, 5)

In [30]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr2d.sum()

300

In [32]:
arr2d.sum(axis=0) # across the columns

array([50, 55, 60, 65, 70])

In [33]:
arr2d.sum(axis=1) #across the rows

array([ 10,  35,  60,  85, 110])

In [47]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [58]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [59]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [60]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
np.random.rand(1)

array([0.84888504])

In [57]:
np.random.randn(25)

array([-0.35600858,  0.18668647, -0.65502404, -0.36703515,  0.51918695,
        0.58652558, -0.34778468, -1.0893721 , -0.87214762,  0.11379098,
       -1.0474066 ,  0.83732422,  2.18846339, -1.03292891,  0.06102283,
       -0.67547809, -0.50653592, -1.07571997,  0.50413361,  0.0700501 ,
       -0.19274955,  2.1247343 , -0.84296213,  0.87892737,  0.64848234])

In [64]:
np.arange(0.01, 1.01, 0.01).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [65]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [66]:
mat = np.arange(1, 26).reshape(5,5)

mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [69]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [76]:
mat[3, 4]

20

In [79]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [81]:
mat[4]

array([21, 22, 23, 24, 25])

In [83]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [84]:
mat.sum()

325

In [85]:
mat.std()

7.211102550927978

In [86]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [87]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [90]:
np.random.seed(101)

np.random.rand(3)

array([0.51639863, 0.57066759, 0.02847423])