<a href="https://colab.research.google.com/github/miller00315/ia_studies/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Introduction to tensors

### Creating tensors

Pytorch tensor sare created using `torch.tensor()`

In [2]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.item()

7

In [6]:
scalar.ndim

0

In [3]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [4]:
# matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [5]:
# tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [9]:
tensor.ndim

3

RuntimeError: a Tensor with 9 elements cannot be converted to Scalar