<a href="https://colab.research.google.com/github/miller00315/ia_studies/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Introduction to tensors

### Creating tensors

Pytorch tensor sare created using `torch.tensor()`

In [2]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.item()

7

In [6]:
scalar.ndim

0

In [3]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [4]:
# matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [5]:
# tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [9]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way neural network learns is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> Look at data -> updtae random numbers -> lok at dat -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [14]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5036, 0.4036, 0.9851, 0.5659],
        [0.0031, 0.0430, 0.2647, 0.9120],
        [0.5511, 0.2160, 0.9837, 0.1791]])

In [15]:
random_tensor_2 = torch.rand(size=(2,3,4))
random_tensor_2

tensor([[[0.9442, 0.8413, 0.3419, 0.1736],
         [0.6774, 0.2077, 0.9463, 0.1715],
         [0.1707, 0.0152, 0.6811, 0.0637]],

        [[0.8816, 0.6485, 0.5807, 0.9495],
         [0.1700, 0.4867, 0.1096, 0.3940],
         [0.5080, 0.4378, 0.4110, 0.2065]]])

In [16]:
random_tesnor_3 = torch.rand(size=(2,3,4,5))
random_tesnor_3

tensor([[[[0.4635, 0.3545, 0.0281, 0.9129, 0.7403],
          [0.5976, 0.2124, 0.7962, 0.1981, 0.8391],
          [0.2562, 0.3267, 0.9933, 0.0305, 0.1573],
          [0.6740, 0.6105, 0.0688, 0.8123, 0.4023]],

         [[0.6572, 0.7424, 0.9220, 0.1320, 0.1831],
          [0.3373, 0.8523, 0.5414, 0.5924, 0.3857],
          [0.8655, 0.7631, 0.1963, 0.2031, 0.6348],
          [0.0629, 0.8987, 0.1362, 0.5378, 0.7909]],

         [[0.9726, 0.4779, 0.6487, 0.4584, 0.4760],
          [0.6071, 0.9603, 0.1519, 0.3272, 0.9659],
          [0.7663, 0.3617, 0.2101, 0.3972, 0.5984],
          [0.1438, 0.1315, 0.8894, 0.6205, 0.0231]]],


        [[[0.6450, 0.9956, 0.2329, 0.6761, 0.9889],
          [0.4031, 0.2850, 0.6194, 0.7663, 0.7440],
          [0.4246, 0.0602, 0.3709, 0.0275, 0.9635],
          [0.7087, 0.2389, 0.1640, 0.1628, 0.6356]],

         [[0.4470, 0.7686, 0.0807, 0.4186, 0.6175],
          [0.8342, 0.5597, 0.7282, 0.3256, 0.3108],
          [0.6089, 0.2648, 0.5209, 0.4617, 0.9576],
  

In [17]:
random_tesnor_4 = torch.rand(size=(2,3,4,5,6))
random_tesnor_4

tensor([[[[[0.6823, 0.1219, 0.3129, 0.5226, 0.6097, 0.4128],
           [0.2578, 0.4576, 0.1571, 0.6037, 0.8818, 0.7301],
           [0.2150, 0.7974, 0.6722, 0.5299, 0.3174, 0.6049],
           [0.0519, 0.2940, 0.4290, 0.7634, 0.3030, 0.4610],
           [0.7349, 0.3821, 0.8751, 0.4078, 0.1742, 0.5654]],

          [[0.9504, 0.0459, 0.3393, 0.4347, 0.8682, 0.0272],
           [0.9277, 0.4727, 0.2362, 0.9484, 0.4433, 0.7660],
           [0.1634, 0.9789, 0.2332, 0.5758, 0.1555, 0.6239],
           [0.7907, 0.3852, 0.1541, 0.0836, 0.2082, 0.0084],
           [0.2656, 0.8236, 0.1651, 0.2594, 0.2057, 0.9521]],

          [[0.3845, 0.1292, 0.5031, 0.8542, 0.0804, 0.4501],
           [0.7466, 0.0041, 0.5592, 0.5535, 0.8194, 0.5986],
           [0.5363, 0.0313, 0.9828, 0.8407, 0.5178, 0.8315],
           [0.7770, 0.5255, 0.9858, 0.7912, 0.0040, 0.2468],
           [0.8210, 0.3403, 0.8250, 0.2769, 0.2082, 0.9005]],

          [[0.8325, 0.4382, 0.1393, 0.5101, 0.9913, 0.5093],
           [0.4893

In [24]:
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [21]:
random_image_size_tensor

tensor([[[0.5339, 0.9240, 0.9606],
         [0.4792, 0.8491, 0.3108],
         [0.7816, 0.1109, 0.8942],
         ...,
         [0.1925, 0.3323, 0.2635],
         [0.4504, 0.1159, 0.2433],
         [0.6701, 0.9559, 0.9898]],

        [[0.9619, 0.7646, 0.7513],
         [0.3763, 0.1633, 0.3334],
         [0.1832, 0.3108, 0.7427],
         ...,
         [0.1423, 0.2722, 0.4134],
         [0.3279, 0.1588, 0.5159],
         [0.3042, 0.3253, 0.6774]],

        [[0.0478, 0.8841, 0.9733],
         [0.6044, 0.1472, 0.9447],
         [0.5909, 0.1255, 0.0902],
         ...,
         [0.6390, 0.4072, 0.7291],
         [0.5087, 0.2338, 0.3087],
         [0.1316, 0.2891, 0.9032]],

        ...,

        [[0.5599, 0.4631, 0.0089],
         [0.4027, 0.3585, 0.2652],
         [0.0384, 0.7352, 0.1428],
         ...,
         [0.8328, 0.0806, 0.8897],
         [0.8835, 0.1224, 0.7130],
         [0.3927, 0.4120, 0.3490]],

        [[0.0066, 0.6970, 0.6342],
         [0.6072, 0.3967, 0.4020],
         [0.

In [26]:
torch.zeros(size=(3,4,3,3))

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

In [27]:
torch.ones(size=(4,5,6))

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])

In [33]:
torch.rand(size=(3, 3)) * torch.ones(size=(3,3))

tensor([[0.6918, 0.4453, 0.0983],
        [0.6661, 0.7835, 0.9353],
        [0.9437, 0.2489, 0.5875]])