<a href="https://colab.research.google.com/github/miller00315/ia_studies/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Introduction to tensors

### Creating tensors

Pytorch tensor sare created using `torch.tensor()`

In [2]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.item()

7

In [4]:
scalar.ndim

0

In [5]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
# matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [9]:
# tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [10]:
tensor.ndim

3

In [11]:
tensor.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way neural network learns is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> Look at data -> updtae random numbers -> lok at dat -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [12]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7510, 0.1843, 0.9296, 0.5762],
        [0.5468, 0.0726, 0.5319, 0.5234],
        [0.5895, 0.0255, 0.2451, 0.0969]])

In [13]:
random_tensor_2 = torch.rand(size=(2,3,4))
random_tensor_2

tensor([[[0.8448, 0.7774, 0.4803, 0.5236],
         [0.7501, 0.3339, 0.3649, 0.3592],
         [0.3784, 0.1294, 0.9201, 0.4370]],

        [[0.8446, 0.9750, 0.1780, 0.2395],
         [0.0629, 0.7714, 0.0479, 0.8127],
         [0.5267, 0.6289, 0.0351, 0.0127]]])

In [14]:
random_tesnor_3 = torch.rand(size=(2,3,4,5))
random_tesnor_3

tensor([[[[0.5466, 0.9169, 0.9358, 0.6389, 0.3275],
          [0.3960, 0.0557, 0.2041, 0.5313, 0.0014],
          [0.3629, 0.6475, 0.5805, 0.7264, 0.4828],
          [0.5529, 0.0820, 0.8810, 0.9409, 0.8634]],

         [[0.5299, 0.4759, 0.3361, 0.6102, 0.7326],
          [0.0268, 0.9292, 0.2488, 0.4325, 0.5183],
          [0.9723, 0.7130, 0.2443, 0.6944, 0.8638],
          [0.2064, 0.2318, 0.7502, 0.3177, 0.5874]],

         [[0.0899, 0.6412, 0.8068, 0.9850, 0.4277],
          [0.4038, 0.9910, 0.6984, 0.5283, 0.5180],
          [0.2070, 0.0213, 0.4504, 0.4996, 0.6511],
          [0.6473, 0.3419, 0.9227, 0.9992, 0.6310]]],


        [[[0.5817, 0.9766, 0.0079, 0.4518, 0.2321],
          [0.0116, 0.4029, 0.0884, 0.9533, 0.2701],
          [0.1346, 0.6662, 0.8344, 0.6928, 0.9836],
          [0.7972, 0.6577, 0.6643, 0.9095, 0.9085]],

         [[0.1738, 0.2960, 0.4905, 0.5132, 0.9929],
          [0.6491, 0.3765, 0.4507, 0.2476, 0.6123],
          [0.3318, 0.8761, 0.2020, 0.4704, 0.3485],
  

In [15]:
random_tesnor_4 = torch.rand(size=(2,3,4,5,6))
random_tesnor_4

tensor([[[[[7.7098e-01, 5.1314e-01, 2.3267e-01, 3.8494e-01, 9.5334e-01,
            1.0170e-01],
           [9.6178e-01, 9.5170e-01, 8.2823e-01, 2.6490e-01, 5.2210e-01,
            5.9004e-01],
           [6.4769e-01, 5.0560e-01, 8.6015e-01, 8.2898e-01, 8.0434e-01,
            6.8809e-01],
           [7.0212e-01, 4.5408e-01, 3.1506e-02, 2.3807e-01, 7.8652e-01,
            6.0235e-01],
           [5.5255e-01, 4.4196e-02, 7.3121e-01, 7.5218e-01, 9.7224e-01,
            3.5295e-01]],

          [[8.2002e-01, 5.4391e-01, 2.1805e-01, 3.2541e-01, 7.5441e-01,
            5.3814e-01],
           [1.6248e-01, 4.1532e-01, 7.0532e-01, 4.8333e-02, 6.6827e-01,
            2.0795e-01],
           [6.8400e-01, 5.3676e-01, 4.3009e-01, 2.2023e-01, 7.7539e-01,
            4.8875e-01],
           [9.3384e-01, 7.3608e-01, 4.5324e-01, 8.8246e-01, 7.5284e-01,
            2.0397e-01],
           [3.4637e-01, 3.5952e-01, 8.2935e-01, 9.6774e-01, 5.4212e-01,
            4.0959e-01]],

          [[2.4374e-01, 2.

In [16]:
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [17]:
random_image_size_tensor

tensor([[[0.2879, 0.0362, 0.1220,  ..., 0.4471, 0.7526, 0.8556],
         [0.7918, 0.4681, 0.6607,  ..., 0.0827, 0.3179, 0.6339],
         [0.0495, 0.8765, 0.6954,  ..., 0.0639, 0.1724, 0.2154],
         ...,
         [0.0496, 0.1696, 0.0886,  ..., 0.5619, 0.1021, 0.6978],
         [0.2477, 0.6575, 0.6109,  ..., 0.1165, 0.8708, 0.9127],
         [0.3591, 0.5185, 0.3262,  ..., 0.0028, 0.1966, 0.3386]],

        [[0.7798, 0.9221, 0.7218,  ..., 0.5219, 0.8680, 0.7325],
         [0.4059, 0.6019, 0.9664,  ..., 0.7967, 0.4050, 0.2698],
         [0.0758, 0.2752, 0.1558,  ..., 0.0680, 0.0289, 0.0479],
         ...,
         [0.8165, 0.2286, 0.5004,  ..., 0.2157, 0.8743, 0.0267],
         [0.8059, 0.6929, 0.1835,  ..., 0.1003, 0.5253, 0.4685],
         [0.6785, 0.5102, 0.2684,  ..., 0.6182, 0.4536, 0.3048]],

        [[0.1513, 0.2417, 0.0615,  ..., 0.7888, 0.7183, 0.8802],
         [0.1369, 0.9849, 0.5840,  ..., 0.3630, 0.6066, 0.5166],
         [0.0294, 0.4049, 0.2311,  ..., 0.4395, 0.2321, 0.

In [18]:
torch.zeros(size=(3,4,3,3))

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

In [19]:
torch.ones(size=(4,5,6))

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])

In [20]:
torch.rand(size=(3, 3)) * torch.ones(size=(3,3))

tensor([[0.4549, 0.8998, 0.4995],
        [0.5330, 0.6580, 0.5728],
        [0.8028, 0.6383, 0.1619]])

## Creating a range of tensors and tensors-like

In [21]:
# Use torch.range()

torch.range(0, 10)

<ipython-input-21-c0ef42c5744d>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ten_zeros = torch.zeros_like(input=torch.arange(0, 10))
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [24]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device='cuda', # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor operation

float_32_tensor, float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.], device='cuda:0'),
 torch.Size([3]),
 torch.float32,
 device(type='cuda', index=0))

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [26]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [27]:
long_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
long_tensor

tensor([3, 6, 9])

### Getting information from tensors

1. tensor not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. tensor not on right device - to get device from a tensor, can use `tensor.device`

In [28]:
# Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4028, 0.0952, 0.0326, 0.7479],
        [0.5232, 0.9058, 0.2124, 0.4060],
        [0.0189, 0.4976, 0.4387, 0.6260]])

In [29]:
# Find out details aboute some tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4028, 0.0952, 0.0326, 0.7479],
        [0.5232, 0.9058, 0.2124, 0.4060],
        [0.0189, 0.4976, 0.4387, 0.6260]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [30]:
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulating Tensors (tensors operations)

Tensors operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [31]:
# Create a tensor and add ten to it

tensor = torch.tensor([1,2,3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [32]:
# Multiply tensor by 10
tensor = tensor * 10

tensor

tensor([110, 120, 130])

In [33]:
tensor = tensor - 10

tensor

tensor([100, 110, 120])

In [34]:
tensor / 10

tensor([10., 11., 12.])

In [35]:
torch.mul(tensor, 10)

tensor([1000, 1100, 1200])

In [36]:
torch.add(tensor, 10)

tensor([110, 120, 130])

### Matrix multiplication

[Matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix are thw sahpe of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [42]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.2071, 0.7487, 1.0718],
        [0.0969, 0.3605, 0.5623],
        [0.1437, 0.5231, 0.7655]])

In [37]:
# Element wise muliplication
print((tensor, "*", tensor))
print(torch.mul(tensor, tensor))

(tensor([100, 110, 120]), '*', tensor([100, 110, 120]))
tensor([10000, 12100, 14400])


In [38]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(36500)

In [41]:
tensor @ tensor

tensor(36500)

In [39]:
%%time

value = 0

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 268 µs, sys: 63 µs, total: 331 µs
Wall time: 393 µs


tensor(36500)

In [40]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 31 µs, sys: 7 µs, total: 38 µs
Wall time: 41.7 µs


tensor(36500)

### One of the most common errors in deep learning: shape errors

In [49]:
# shape for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype=torch.float32)


tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]], dtype=torch.float32)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [50]:
torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [46]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [47]:
tensor_B, tensor_B.T

(tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]))

In [48]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [51]:
# Finding the min, max mean, sum etc(tensor, aggregation)

x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
x.min()

tensor(0)

In [53]:
x.max()

tensor(90)

In [56]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 dattyp to work
torch.mean(x.type(torch.float32))

tensor(45.)

In [57]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [58]:
# Returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [59]:
# Returns index position of target tensor where the maximum value occurs
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing, and unsqueesing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [66]:
# Let's create a tensor
x = torch.arange(0., 10.)

x, x.shape

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([10]))

In [68]:
# Adda a extra dimension
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 10]))

In [69]:
x_reshaped = x.reshape(10, 1)
x_reshaped, x_reshaped.shape

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([10, 1]))

In [70]:
x.reshape(2, 5)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [71]:
# Change the view
z = x.view(1, 10)
z, z.shape

(tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 10]))

In [72]:
# Changing the z changes x (because a view of tensor shanre the same memory as theoriginla input)
z[:, 0] = 5
z, x

(tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [73]:
# Stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [75]:
# torch.squeeze - removes all single dimensions from a target tensor
x_reshaped.shape, x_reshaped.squeeze(), x_reshaped.squeeze().shape

(torch.Size([10, 1]),
 tensor([5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([10]))

In [78]:
# adds a single dimension to a target tensor at a specific dim (dimension )
x_reshaped.unsqueeze(dim=0).shape, x_reshaped.unsqueeze(dim=1).shape

(torch.Size([1, 10, 1]), torch.Size([10, 1, 1]))

In [79]:
x_reshaped.unsqueeze(dim=0)

tensor([[[5.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

In [80]:
x_reshaped.unsqueeze(dim=1)

tensor([[[5.]],

        [[1.]],

        [[2.]],

        [[3.]],

        [[4.]],

        [[5.]],

        [[6.]],

        [[7.]],

        [[8.]],

        [[9.]]])

In [ ]:
# Permute the diensions in a specific order


In [83]:
x = torch.rand(size=(2, 3, 5))
x.shape

torch.Size([2, 3, 5])

In [84]:
x

tensor([[[0.6366, 0.8864, 0.1096, 0.4421, 0.1417],
         [0.5044, 0.3944, 0.2550, 0.5698, 0.2786],
         [0.6201, 0.2757, 0.7859, 0.9690, 0.0606]],

        [[0.7561, 0.0562, 0.0766, 0.8271, 0.6428],
         [0.8523, 0.7150, 0.2971, 0.1727, 0.3832],
         [0.0606, 0.7880, 0.0292, 0.8000, 0.9345]]])

In [86]:
torch.permute(x, (1, 0, 2)), torch.permute(x, (0, 2, 1)).shape

(tensor([[[0.6366, 0.8864, 0.1096, 0.4421, 0.1417],
          [0.7561, 0.0562, 0.0766, 0.8271, 0.6428]],
 
         [[0.5044, 0.3944, 0.2550, 0.5698, 0.2786],
          [0.8523, 0.7150, 0.2971, 0.1727, 0.3832]],
 
         [[0.6201, 0.2757, 0.7859, 0.9690, 0.0606],
          [0.0606, 0.7880, 0.0292, 0.8000, 0.9345]]]),
 torch.Size([2, 5, 3]))

In [87]:
# Rearange the dimensions of a target tensor ina specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

x_original.shape

torch.Size([224, 224, 3])

In [88]:
# permute the original tensor to rearange the axis (or dim)
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape # [colour_channels, height, width]

torch.Size([3, 224, 224])

In [89]:
x_permuted

tensor([[[0.4463, 0.1727, 0.0889,  ..., 0.2080, 0.1226, 0.5841],
         [0.9712, 0.9970, 0.9687,  ..., 0.5643, 0.5333, 0.5920],
         [0.8071, 0.7910, 0.3738,  ..., 0.9054, 0.9466, 0.9349],
         ...,
         [0.2174, 0.4598, 0.1397,  ..., 0.8885, 0.6486, 0.6263],
         [0.1618, 0.1813, 0.3688,  ..., 0.6661, 0.5539, 0.0961],
         [0.9729, 0.0215, 0.1311,  ..., 0.5322, 0.5631, 0.0370]],

        [[0.7117, 0.3830, 0.4939,  ..., 0.3580, 0.3956, 0.3747],
         [0.4858, 0.2171, 0.3374,  ..., 0.6880, 0.7840, 0.8880],
         [0.8512, 0.0408, 0.4069,  ..., 0.8650, 0.0267, 0.8135],
         ...,
         [0.9361, 0.6334, 0.3577,  ..., 0.8299, 0.3215, 0.4188],
         [0.1140, 0.3900, 0.8300,  ..., 0.5212, 0.3399, 0.6891],
         [0.7372, 0.6321, 0.7742,  ..., 0.4833, 0.6179, 0.2888]],

        [[0.1785, 0.7435, 0.0451,  ..., 0.3599, 0.1512, 0.9257],
         [0.8096, 0.9631, 0.8592,  ..., 0.6126, 0.7944, 0.2341],
         [0.6045, 0.9320, 0.7172,  ..., 0.0399, 0.6224, 0.

In [90]:
x_original[0, 0, 0]
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(0.4463), tensor(0.4463))

## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with NumPy

In [91]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [92]:
# let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [93]:
# Let's index on the middle bracket
x[0, 0]

tensor([1, 2, 3])

In [95]:
# Let's index on the most inner bracket (last dimmension)
x[0][0][0], x[0, 0, 0]

(tensor(1), tensor(1))

In [96]:
# Tou can also use ":" to select "all" of a target dimension

x[:, 0]


tensor([[1, 2, 3]])

In [103]:
# Get all values of 0th and 1st dimentions buth only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [104]:
# Get all values of 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [105]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, 1]

tensor(2)

In [110]:
# Index on x to return 9
x[:,2, 2]
# Index to return 3, 6, 9

x[:, :, 2]

tensor([[3, 6, 9]])

In [111]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## PyTorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library.

And because of this,, PyTorhc has functionality to interact with it.

* Data in NumPy, want it PyTorhc tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [112]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [113]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [114]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [116]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update reandom numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [117]:
torch.rand(3, 3)

tensor([[0.9630, 0.6935, 0.9903],
        [0.7806, 0.6431, 0.5749],
        [0.0390, 0.0713, 0.5122]])

In [119]:
# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6684, 0.9549, 0.8064, 0.3774],
        [0.7350, 0.9696, 0.7427, 0.5624],
        [0.1010, 0.4969, 0.9364, 0.2860]])
tensor([[0.8645, 0.2744, 0.2778, 0.8143],
        [0.0451, 0.6753, 0.7014, 0.1879],
        [0.2763, 0.7365, 0.3048, 0.4812]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [120]:
# Let's make some random but reproducible tensors
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [121]:
random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors and PyTorch objects on the GPUs (and makin faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

In [ ]:
### 1. Getting a GPU

1 Easist - Use the google colab for a free GPU's

2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options

3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them using your browser.



In [122]:
!nvidia-smi

Mon Jun 24 02:32:02 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   72C    P0              30W /  70W |    121MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [123]:
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU, it's best practice to setup device agnostic code.

E. g. run on GPU if available, else default to CPU

In [124]:
# Steup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [125]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [126]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [127]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')