<a href="https://colab.research.google.com/github/miller00315/ia_studies/blob/main/tensorflow_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

print(tf.__version__)

2.17.0


** Declaring variables **

In [3]:
v0 = 42
v1 = tf.Variable(42) # rank 0 tensor
v2 = tf.Variable([1, 2]) # rank 1 tensor
v3 = tf.Variable([[1, 2], [3, 4]]) # rank 2 tensor

In [4]:
v0

42

In [5]:
v1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>

In [6]:
v2

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [7]:
v3

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [8]:
v1.assign(10)

v1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [9]:
c1 = tf.constant(42)
c1

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [10]:
c2 = tf.constant(62, dtype=tf.float64)
c2

<tf.Tensor: shape=(), dtype=float64, numpy=62.0>

**Shapping a tensor**

In [16]:
t4 = tf.Variable([[1, 2, 3], [4, 5, 6]])
t4

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [17]:
t5  = tf.reshape(t4, [1, 6])
t5

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]], dtype=int32)>

**Ranking (dimensions) of a tensor**

In [18]:
tf.rank(t4)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

**Specifing a element of a tensor**

In [19]:
t6 = t4[0, 1]

t6

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [20]:
t6.numpy()

2

**Cast a tensor to numpy**

In [21]:
t6.numpy()

2

**Finding the number of elements of a tensor**

In [22]:
tf.size(t4)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

**Specifing element-wise tensor operations**

In [28]:
t7 = tf.Variable([1, 2])
t8 = tf.Variable([2, 2])


In [29]:
(t7 * t8).numpy()

array([2, 4], dtype=int32)

**Tranposing and matrix multiplication**

In [30]:
c1 = tf.constant([[1, 2]])

c2 = tf.constant([[3, 4]])

tf.matmul(c1, tf.transpose(c2))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[11]], dtype=int32)>

**Type casting**

In [ ]:
c1

In [31]:
c3 = tf.cast(c1, tf.int64)

c3

<tf.Tensor: shape=(1, 2), dtype=int64, numpy=array([[1, 2]])>

**Declaring ragged tensor**

In [32]:
raggeed = tf.ragged.constant([[1], [], [1, 2], [4, 5, 6]])

raggeed

<tf.RaggedTensor [[1], [], [1, 2], [4, 5, 6]]>

## **Tensor flow Operations**

**Finding mean**

In [35]:
tf.reduce_mean([1,2,3,4,5])

<tf.Tensor: shape=(), dtype=int32, numpy=3>

mean across columns use axis = 0

In [36]:
v3 = tf.Variable([[1, 2], [3, 4]])
tf.reduce_mean(v3, axis=0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

mean across rows use axis = 1

In [37]:
v3 = tf.Variable([[1, 2], [3, 4]])
tf.reduce_mean(v3, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

##**Generating tensor with random values**

Random values are frequntly required when developing neural networks

**tf.random.normal()**

In [38]:
tf.random.normal([3, 2], mean=2, stddev=2, dtype=tf.float32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.8314706,  4.5920057],
       [-0.7486701,  0.4354756],
       [ 4.788207 ,  1.4967747]], dtype=float32)>

**tf.random.uniform()**

In [39]:
tf.random.uniform([3, 2], minval=0, maxval=5, dtype=tf.float32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3.2503128 , 0.01602769],
       [4.0029726 , 2.4873953 ],
       [0.52552044, 4.1736403 ]], dtype=float32)>

If you want the random values generated to be repeatable, then use tf.random.set_seed()

In [41]:
tf.random.set_seed(111)
tf.random.normal([3, 2], mean=2, stddev=2, dtype=tf.float32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3.5116253, 5.0894527],
       [5.2631207, 1.6026206],
       [2.1765652, 2.034233 ]], dtype=float32)>

**Add two tensors**

In [42]:
v1 = tf.Variable([3, 4])
v2 = tf.Variable([2, 1])

v1 + v2

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>

**Concatinate two tensors**

In [43]:
v1 = tf.Variable([3, 4])
v2 = tf.Variable([2, 1])

v3 = tf.concat([v1, v2], axis=0)

v3

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 2, 1], dtype=int32)>

In [44]:
v4 = tf.stack([v1, v2], axis=1)

v4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 2],
       [4, 1]], dtype=int32)>

**Finding minimum and maximum element**

In [50]:
v1 = tf.Variable([[1, 2], [3, 4]])
v2 = tf.Variable([[6, 7], [8, 9]])

v3 = tf.concat([v1, v2], axis=0)

v3

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]], dtype=int32)>

In [51]:
v4 = tf.concat([v1, v2], axis=1)
v4

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 6, 7],
       [3, 4, 8, 9]], dtype=int32)>

**Finding minimum and maximum element**

In [55]:
v1 = tf.Variable([4, 2, 3, 5])

tf.argmax(input=v1).numpy()

3

In [56]:
tf.argmin(input=v1).numpy()

1

**Saving and restoring tensor values using a checkpoint**

In [58]:
variable = tf.Variable([1, 2], [3, 4])

checkpoint = tf.train.Checkpoint(var=variable)

save_path = checkpoint.save('./vars')

In [59]:
save_path

'./vars-1'

In [60]:
variable.assign([0, 0], [0, 0])

variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([0, 0], dtype=int32)>

In [61]:
checkpoint.restore(save_path)

variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>